name: Pruebas automáticas en Python

on:
  push:
    branches: [ "joel" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install requirements.txt

    - name: Ejecutar pruebas
      run: 
        pytest
        ruff check .

